_target_: tuna.models._transformer.Transformer

type: t-fc
architecture:
  protein_dim: 640
  hid_dim: 64
  ff_dim: 256
  n_layers: 1
  n_heads: 8
  dropout: 0.2
  out_targets: 1
  spectral_norm: False
  llgp: False