defaults:
  - model: None # options [tuna, tuna-gp, esm-mlp, esm-gp]
  - dataset: None # options [gold-standard, mouse, fly, worm, yeast, ecoli]
  - _self_

seed: 42

wandb:
  project: "TUnA-R"

trainer:
  accelerator: auto
  devices: auto

datamodule:
  max_sequence_length: 512
  num_workers: 4
  pin_memory: True
  persistent_workers: True
