model:
  embedding_dim: 640
  hid_dim: 64
  dropout: 0.1
  llgp: False
  spectral_norm: False
  out_targets: 1

training:
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.00001
  epochs: 9
 
optimizer:
  step_size: 2
  gamma: 0.93
