model:
  embedding_dim: 640
  hid_dim: 64
  ff_dim: 256
  n_layers: 1
  n_heads: 8

  max_sequence_length: 512
  dropout: 0.2
  llgp: True
  spectral_norm: True
  rffs: 4096
  out_targets: 1
  gp_cov_momentum: -1
  gp_ridge_penalty: 1
  likelihood_function: 'binary_logistic'

training:
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.00001
  epochs: 14
 
optimizer:
  step_size: 2
  gamma: 0.93
